"""What is actually installed, whoever wrote it (GRPH-354 / PRD-16).

`artifact_recommendations` only ever holds artifacts this pipeline GENERATED, so usage
telemetry was blind to every skill, hook, agent and rule a human wrote by hand — reporting a
population of zero on an install whose `.claude/` directory was full of them. Those are the
artifacts actually spending context on every turn, which is the cost PRD-16 exists to
control.

The table is a record of observation, never a licence to act. A row means "this was seen at
this path with these contents"; nothing here authorises writing, moving or deleting the file
it describes.

`state` is the finding, and the three values are genuinely different claims:

  present  — seen, and if machine-owned it still matches what we rendered.
  forked   — machine-owned and a human has since edited it. `install_plan` refuses to
             re-render these: updates are FULL re-renders, so writing would silently discard
             the edit — the trust failure propose-only exists to prevent.
  orphaned — inventoried before, absent from the latest scan OF THE SAME ROOT. Flagged and
             left alone; a file missing from one scan may be an unmounted volume, and
             retiring on that reading deletes working artifacts.

`root` is stored rather than derived because it scopes orphaning. A scan of `~/.claude` says
nothing about what lives under `~/work/.cursor`, and marking those missing because this pass
never looked there would be an absence read as a finding.

Hand-written, not autogenerated. `--autogenerate` produced ~450 lines here: the table plus
several hundred lines of unrelated nullable drift, and it proposed DROPPING both HNSW vector
indexes (`ix_memory_shards_embedding`, `ix_code_nodes_embedding`), which would have silently
destroyed vector-search recall. AGENTS.md warns about exactly this.

Revision ID: 0062
Revises: 0061
"""
from alembic import op
import sqlalchemy as sa

revision = "0062"
down_revision = "0061"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "artifact_inventory",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("project_id", sa.String(), sa.ForeignKey("projects.id"), nullable=True),
        sa.Column("root", sa.String(), nullable=False, server_default=""),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False, server_default=""),
        sa.Column("content_hash", sa.String(), nullable=False, server_default=""),
        sa.Column("size", sa.Integer(), nullable=False, server_default="0"),
        # NULL = human-authored, which is the majority and the whole point of the table.
        sa.Column("recommendation_id", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(), nullable=False, server_default="present"),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )
    op.create_index("ix_artifact_inventory_root", "artifact_inventory", ["root"])
    op.create_index("ix_artifact_inventory_path", "artifact_inventory", ["path"])
    op.create_index("ix_artifact_inventory_rec", "artifact_inventory",
                    ["recommendation_id"])
    op.create_index("ix_artifact_inventory_state", "artifact_inventory", ["state"])


def downgrade() -> None:
    op.drop_index("ix_artifact_inventory_state", table_name="artifact_inventory")
    op.drop_index("ix_artifact_inventory_rec", table_name="artifact_inventory")
    op.drop_index("ix_artifact_inventory_path", table_name="artifact_inventory")
    op.drop_index("ix_artifact_inventory_root", table_name="artifact_inventory")
    op.drop_table("artifact_inventory")
