"""Agents, reservations, and the review handoff (GRPH-331 / PRD-17).

Nothing counted agents before. `agent_id` was a self-declared string defaulting to the API
key's name, so three terminals sharing one key were a single agent to the server — no roles
could be assigned between them, nothing stopped one signing off its own work, and the roster
could not answer who was out there.

Four changes, and the interesting ones are the constraints they make expressible:

- **`agents`** — the registry. `(project_id, number)` is unique so the PRD-13 key renders
  from the project's current tag (`GRPH-A3`) and survives a retag untouched. Labels are
  deliberately NOT unique: two identical Claude Code windows on one machine is a legitimate
  fleet shape, and de-duplicating by label would merge two real agents into one.
- **`area_reservations`** — what an agent holds while work is in flight, expiring on the
  same lease clock rather than on an explicit release the holder may die before sending.
- **`api_keys.roles` / `.fleet_wave`** — the role CEILING, and the tag that lets "End wave"
  revoke exactly the keys the Fleet view minted and never one a human made by hand.
- **`items.branch` / `.reviewed_by` / `.bounce_pinned_to` / `.bounce_pinned_until`** — the
  review handoff. `reviewed_by` exists as a column so the load-bearing invariant of PRD-17
  ("an agent cannot pass its own work") is a comparison against `claimed_by` rather than
  something inferred from an event log.

**Existing keys are backfilled to all three roles.** A key resolving to no roles would make
every agent authenticating with it unable to work — an absence behaving like a decision — so
the migration writes the permissive value rather than leaving NULL to be interpreted.

Hand-written, not autogenerated: `--autogenerate` on this schema emits several hundred lines
of unrelated nullable drift and proposes DROPPING both HNSW vector indexes, which would
silently destroy search recall (see 0062, and AGENTS.md).

Revision ID: 0063
Revises: 0062
"""
from alembic import op
import sqlalchemy as sa

revision = "0063"
down_revision = "0062"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "agents",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("project_id", sa.String(), sa.ForeignKey("projects.id"), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.String(), sa.ForeignKey("api_keys.id"), nullable=True),
        sa.Column("label", sa.String(), nullable=False, server_default=""),
        sa.Column("active_role", sa.String(), nullable=False, server_default="worker"),
        sa.Column("role_assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role_acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("worktree", sa.String(), nullable=False, server_default=""),
        sa.Column("branch", sa.String(), nullable=False, server_default=""),
        sa.Column("branch_orphaned", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("state", sa.String(), nullable=False, server_default="idle"),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        # The PRD-13 guarantee: one number per kind per project, so the rendered key is
        # unique and a retag moves nothing.
        sa.UniqueConstraint("project_id", "number", name="uq_agent_project_number"),
    )
    op.create_index("ix_agents_project", "agents", ["project_id"])
    op.create_index("ix_agents_state", "agents", ["state"])
    op.create_index("ix_agents_last_seen", "agents", ["last_seen_at"])

    op.create_table(
        "area_reservations",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("agent_id", sa.String(), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("item_id", sa.String(), sa.ForeignKey("items.id"), nullable=False),
        sa.Column("area", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )
    op.create_index("ix_area_res_agent", "area_reservations", ["agent_id"])
    op.create_index("ix_area_res_item", "area_reservations", ["item_id"])
    op.create_index("ix_area_res_area", "area_reservations", ["area"])
    op.create_index("ix_area_res_expires", "area_reservations", ["expires_at"])

    op.add_column("api_keys", sa.Column("roles", sa.JSON(), nullable=False, server_default="[]"))
    op.add_column("api_keys", sa.Column("fleet_wave", sa.String(), nullable=True))
    op.create_index("ix_api_keys_fleet_wave", "api_keys", ["fleet_wave"])
    # Backfill: every existing credential keeps working at full eligibility. Written rather
    # than left empty because "no roles" and "roles unspecified" must not look the same.
    op.execute("""UPDATE api_keys SET roles = '["planner", "worker", "reviewer"]'""")

    op.add_column("items", sa.Column("branch", sa.String(), nullable=False, server_default=""))
    op.add_column("items", sa.Column("reviewed_by", sa.String(), nullable=True))
    op.add_column("items", sa.Column("bounce_pinned_to", sa.String(), nullable=True))
    op.add_column("items", sa.Column("bounce_pinned_until", sa.DateTime(timezone=True),
                                     nullable=True))


def downgrade() -> None:
    op.drop_column("items", "bounce_pinned_until")
    op.drop_column("items", "bounce_pinned_to")
    op.drop_column("items", "reviewed_by")
    op.drop_column("items", "branch")
    op.drop_index("ix_api_keys_fleet_wave", table_name="api_keys")
    op.drop_column("api_keys", "fleet_wave")
    op.drop_column("api_keys", "roles")
    op.drop_index("ix_area_res_expires", table_name="area_reservations")
    op.drop_index("ix_area_res_area", table_name="area_reservations")
    op.drop_index("ix_area_res_item", table_name="area_reservations")
    op.drop_index("ix_area_res_agent", table_name="area_reservations")
    op.drop_table("area_reservations")
    op.drop_index("ix_agents_last_seen", table_name="agents")
    op.drop_index("ix_agents_state", table_name="agents")
    op.drop_index("ix_agents_project", table_name="agents")
    op.drop_table("agents")
