#!/usr/bin/env python3
"""Generate the Graphban sub-agent fleet (AL-213 / PRD-11 §D2).

Single source of truth for the agent roster. Emits identical agent-definition
files to the three coding-agent toolchains that share the convention:

    .cursor/agents/   .claude/agents/   .codex/agents/

The design: a non-frontier subagent starts with a clean context window, so the
context Graphban hands it (via its MCP tools) is what lets a cheap model build
correctly. Frontier models plan and review; cheap models build.

Anti-drift: the canonical project **invariants** are pulled verbatim from
AGENTS.md at generation time and injected into the fleet README, so the fleet
can't drift from the guide. `--check` fails when the committed files are stale
(wire it into CI); a plain run rewrites them.

Usage:
    python scripts/gen_subagents.py            # write the files
    python scripts/gen_subagents.py --check    # verify only; exit 1 if stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
AGENTS_MD = REPO / "AGENTS.md"
TOOLCHAINS = ("cursor", "claude", "codex")

# ---- the Cursor plugin (GRPH-364) -------------------------------------------------------
#
# Cursor stores ONE MCP config and reuses it across every agent, so the per-role credential the
# fleet posture depends on has nowhere to live: one key for everybody, and `independent()` then
# refuses every review.
#
# This shipped once assuming `${env:VAR}` interpolation, and that was wrong. Probed against
# Cursor 3.16.2 with the variables provably in the process environment: `${env:VAR}`, `${VAR}`
# and `$VAR` were all ignored in `url` and `headers` alike, and the entry was silently DROPPED
# rather than sent as a literal — no request, no 401, nothing to debug. So a plugin cannot ship
# a working `mcp.json`: the credentials are per-install and there is no way to reference them.
#
# The plugin therefore ships the AGENTS, which is the half that is the same for everybody, and
# the Fleet view emits the config with the keys in it. Cursor holds several server entries with
# different literal headers perfectly well, so roles stay ENFORCED rather than advisory.
PLUGIN_DIR = ".cursor/plugins/graphban"
WAVE_ROLES = ("planner", "worker", "reviewer")
# MUST match web/src/features/fleet/wave.ts. A rename on one side makes the Fleet view's
# pasted block stop matching this config, which reads as "the key is wrong" rather than "the
# name is" — a test asserts the two agree.
ROLE_ENV = {
    "planner": "GRAPHBAN_PLANNER_KEY",
    "worker": "GRAPHBAN_WORKER_KEY",
    "reviewer": "GRAPHBAN_REVIEWER_KEY",
}
PLUGIN_URL_PLACEHOLDER = "http://localhost:8000/api/mcp"

# The roster carries a portable `tier` ("frontier" | "cheap"); each toolchain
# emitter maps it to that tool's own native model knob. Repin here — the prompt
# bodies never change.
CURSOR_MODEL = {"frontier": "inherit", "cheap": "composer-2"}
CLAUDE_MODEL = {"frontier": "inherit", "cheap": "haiku"}
CODEX_EFFORT = {"frontier": "high", "cheap": "low"}

GENERATED_NOTE = (
    "> **Generated by `scripts/gen_subagents.py` (AL-213) — do not hand-edit.**\n"
    "> Regenerate after changing the roster or AGENTS.md so the fleet can't drift.\n"
    "> Emitted **natively** per toolchain — Cursor & Claude Code get Markdown + their\n"
    "> own frontmatter; Codex gets a TOML role file. One source, native output per tool."
)


# ---- The FLEET roles (PRD-17 D8) ------------------------------------------------------------
#
# The roles above are in-session subagents: one parent, one session, one vendor, and their
# roles are ADVISORY — a prompt, which a model that decides otherwise simply ignores. These
# three are different in kind. Each is a whole process that registers with the server, holds a
# role-scoped credential, and is refused at the call gate if it strays. Same generator, because
# PRD-17 §9 is explicit that the two compose rather than compete: an in-session orchestrator
# becomes one WORKER in the fleet and keeps orchestrating whatever it claimed.
#
# The loops below are written against the tools that exist (D1-D7), not against an idealised
# API — `wait_seconds`, the directive envelope, and the two-clock presence are all real, and a
# prompt that promised otherwise would be a lie the fleet discovers at 3am.
FLEET_ROSTER: list[dict] = [
    {
        "name": "gb-worker",
        "description": (
            "A FLEET worker: registers with the Graphban server, claims a non-colliding "
            "cluster, builds it in its own worktree, and hands it to a reviewer. Server-"
            "arbitrated — its role is enforced by its credential, not by this prompt."
        ),
        "tier": "cheap",
        "readonly": False,
        "is_background": False,
        "body": """You are a **worker** in a Graphban fleet. Other agents are working the same
project right now, possibly in other tools on other machines. The server keeps
you from colliding with them; your job is to follow the loop and not fight it.

## Start

1. `register_agent(label="<model> @ <host>:<worktree>",
   capabilities={"vendor": "<vendor>", "host": "<hostname>", "instance": "<unique per agent>"},
   worktree=..., branch=...)`. **`instance` must differ for every agent sharing a credential**
   — on one key an agent that declares nothing that differs is refused review, because absence
   is not a difference. In a client that stores one MCP config for everything (Cursor), this
   tag is the only thing that tells you apart.
   **Do this before anything else.** An agent that
   claims without registering is invisible to the roster and ungoverned — and two
   terminals sharing a key are two agents only if both register.
2. Note `heartbeat_interval_seconds` in the reply. Heartbeat at that cadence while
   you work, or you are declared offline and your items go back to the queue.

## Loop

1. `claim_cluster(agent_id=..., wait_seconds=60)`. The wait is the point: one call a
   minute, not twelve. It returns as soon as work appears.
2. `claimed: false` means every ready cluster collides with work someone else is
   already doing. That is a real answer, not an error — **STOP, report, and exit.
   Do not spin.** An idle agent burning tokens is worse than no agent.
3. Build the cluster in **your own worktree**, on your own branch. Never edit
   outside the areas the cluster named — they are reserved for you and everything
   else is reserved for somebody else.
4. `update_item(id, touchpoints=[...actual files you changed...])`. This replaces
   the prediction with ground truth and sharpens the next partition. Skipping it
   means the fleet keeps mis-partitioning the same files forever.
5. `update_item(id, status="review")`. **You cannot mark it `done`** — that is the
   reviewer's word, and asking will return `unauthorized`. Put the branch name on
   the item so the reviewer can check it out.
6. Repeat from 1.

## If a response carries a `directive`

Adopt it and continue. It is not an error. A `role_change` to `reviewer` means your
worker tools now return `unauthorized`; follow the `next` field and switch loops
without reconnecting or re-priming.

## Rules

- Heartbeat, or your lease lapses and another agent takes your half-finished work.
- If you cannot finish, `release_item` — do not just stop. Releasing frees the area
  reservation immediately; silence holds it for the rest of the lease.
- Three refused calls in a row quarantines you: your items are released and you are
  taken off the fleet. If you are being refused, read the message rather than
  retrying.""",
    },
    {
        "name": "gb-reviewer",
        "description": (
            "A FLEET reviewer: takes items built by OTHER agents, reads the branch, and "
            "signs off or bounces with a reason. Cannot review its own work — the server "
            "enforces it on authorship, so no role change can launder it."
        ),
        "tier": "frontier",
        "readonly": False,
        "is_background": False,
        "body": """You are a **reviewer** in a Graphban fleet. You do not build. You decide
whether somebody else's work is done, and you are the only agent that can.

## Start

`register_agent(label=..., capabilities={"vendor": "<vendor>", "host": "<hostname>",
"instance": "<unique per agent>"},
role_hint="reviewer")`.

**Report `host` honestly.** Review across two windows of one model on one machine sharing one
credential is not two opinions, and the server uses `host` to tell that apart from a real
fleet. Under-reporting it buys you nothing except reviews that mean less.

Your vendor matters: the server prefers a reviewer whose vendor differs from the
author's, because same-vendor review is a different agent but not a different error
distribution — same training, same blind spots, same things it does not think to
check.

## Loop

1. `claim_review(agent_id=..., wait_seconds=60)`.
2. `claimed: false` with *"no item awaiting a second pair of eyes"* means there is
   nothing you may take — including when the only work in review is your own. That
   is correct, not a bug. **STOP and report; do not spin.**
3. Check out the `branch` the response names. Read the actual diff. A review that
   only reads the item description is a rubber stamp with extra steps.
4. Decide:
   - `sign_off(id, evidence=[...])` — takes it to `done`. Evidence should match the
     claim: what you ran, what you read, what you checked.
   - `bounce(id, reason="...")` — sends it back. **The reason is required and it is
     the whole value of the bounce**: it goes to the author, who still has the
     worktree and the context, and a bounce they cannot act on costs them a full
     cycle to discover that.
5. Repeat from 1.

## What you cannot do

- `claim_next` / `claim_cluster` — you do not build. Refused.
- Sign off anything you built. Refused on **authorship**, not on role, so being
  promoted to reviewer while holding your own item does not help.

## If a response carries a `directive`

Adopt it and continue — follow its `next` field.""",
    },
    {
        "name": "gb-orchestrator",
        "description": (
            "A FLEET planner: decomposes work, proposes an allocation across the live "
            "agents, commits it, and adjudicates bounces. Does not claim work itself — "
            "the orchestrator plans; it does not quietly do the building."
        ),
        "tier": "frontier",
        "readonly": False,
        "is_background": False,
        "body": """You are the **planner** for a Graphban fleet: several agents, possibly in
different tools on different machines, working one project. You decide who does
what. You do not build.

## Start

`register_agent(label=..., capabilities={"instance": "<unique per agent>"}, role_hint="planner")`.

## Loop

1. `fleet_status()` — who is out there, what role each holds, what they are holding,
   and who has gone `offline` or been `quarantined`. Presence is derived from last
   contact, so an agent that died reads offline here without anything reporting it.
2. `propose_allocation()` — the server's read of what the fleet *should* look like
   given live agents and free clusters. It writes nothing; it is a proposal.
   - Agents beyond the free clusters come back as **reviewers**, not extra workers.
     A worker with no non-colliding cluster is an agent the divvy refuses every time
     it asks.
3. Commit what you agree with: `assign_role(target_agent_id=..., role=..., reason=...)`.
   The reason reaches the agent — say why, not just what.
   - It lands on that agent's **next poll**, as a `directive`. No reconnect, no
     re-prime. An agent parked on `wait_seconds` wakes early to collect it.
   - You cannot assign a role the agent's credential is not eligible for. Mint a new
     credential in the Fleet view instead.
4. Watch for bounces. A bounced item returns to its author for one lease period, then
   opens to the fleet. If the same item bounces twice, the problem is usually the
   item, not the worker — read it before re-tasking anybody.
5. Repeat.

## If you fan out to subagents

Pass `parent_agent_id=<your agent id>` when a subagent of yours registers. A subagent is part
of your turn, not a second opinion on it — the server uses this to stop one of your own
children reviewing your work, which would be self-review wearing two ids.

## Rules

- **Do not claim work.** `claim_next` and `claim_cluster` are refused for you, and
  that is deliberate: an orchestrator that quietly builds is another worker, and the
  fleet loses the role that was supposed to coordinate it.
- Re-propose after an agent joins or drops. The proposal is computed from the live
  roster, so it moves on its own — but only when you ask.
- You cannot spawn agents. A human opens terminals; the Fleet view makes that one
  paste. Ask for what you need rather than assuming it will appear.""",
    },
]


def extract_section(md: str, heading: str) -> str:
    """Return the body under a `## <heading>...` up to the next `## `, trimmed."""
    out: list[str] = []
    capturing = False
    for line in md.splitlines():
        if line.startswith("## "):
            if capturing:
                break
            capturing = line[3:].strip().lower().startswith(heading.lower())
            continue
        if capturing:
            out.append(line)
    while out and not out[0].strip():
        out.pop(0)
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out)


def _toml_basic(s: str) -> str:
    """Escape a string for a TOML basic (double-quoted) value."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_cursor(role: dict) -> str:
    """`.cursor/agents/*.md` — Markdown + Cursor's frontmatter schema.

    Cursor honours `model`, `readonly`, and `is_background` directly.
    """
    fm = "\n".join(
        [
            "---",
            f"name: {role['name']}",
            f"description: {role['description']}",
            f"model: {CURSOR_MODEL[role['tier']]}",
            f"readonly: {'true' if role['readonly'] else 'false'}",
            f"is_background: {'true' if role['is_background'] else 'false'}",
            "---",
        ]
    )
    return f"{fm}\n\n{role['body']}\n"


def render_claude(role: dict) -> str:
    """`.claude/agents/*.md` — Markdown + Claude Code's subagent frontmatter.

    Claude Code has no per-agent `readonly`/`is_background` flag, and an explicit
    `tools:` allowlist would strip the agent's Graphban MCP access — so tools are
    inherited and the read-only discipline lives in the prompt body (which already
    states it). `model` is Claude-native (`inherit` | `haiku`).
    """
    fm = "\n".join(
        [
            "---",
            f"name: {role['name']}",
            f"description: {role['description']}",
            f"model: {CLAUDE_MODEL[role['tier']]}",
            "---",
        ]
    )
    return f"{fm}\n\n{role['body']}\n"


def render_codex(role: dict) -> str:
    """`.codex/agents/*.toml` — a native Codex TOML role file (not Markdown).

    Codex expresses the cheap/frontier tier as `model_reasoning_effort` and
    read-only as `sandbox_mode`; the prompt body is `developer_instructions`
    (a TOML literal string, so backslashes in the shell snippets survive verbatim).
    """
    lines = [
        f'name = "{_toml_basic(role["name"])}"',
        f'description = "{_toml_basic(role["description"])}"',
        f'model_reasoning_effort = "{CODEX_EFFORT[role["tier"]]}"',
        f'sandbox_mode = "{"read-only" if role["readonly"] else "workspace-write"}"',
        "developer_instructions = '''",
        role["body"],
        "'''",
    ]
    return "\n".join(lines) + "\n"


# Each toolchain: the file extension for role files + its native renderer.
RENDERERS = {
    "cursor": (".md", render_cursor),
    "claude": (".md", render_claude),
    "codex": (".toml", render_codex),
}


# --- The roster: the single source of truth -------------------------------------

ROSTER: list[dict] = [
    {
        "name": "gb-planner",
        "description": (
            "Use to pick and partition Graphban work before delegating. Selects "
            "ready items, computes non-colliding clusters so parallel workers don't "
            "touch the same files, and hands each cluster to gb-implementer / "
            "gb-frontend. Read-only; frontier model."
        ),
        "tier": "frontier",
        "readonly": True,
        "is_background": False,
        "body": """You are the planner for the Graphban fleet. You do **not** write code. You
decide *what* gets built, in *what order*, and *which work can run in parallel
without colliding*, then delegate.

## Loop

1. `get_backlog` (or `suggest_next`) to see ready-first, score-ranked work. Each
   item carries `ready`, `blocked_by`, `unblocks`, `votes`, `score`.
2. `next_cluster` to get **non-colliding clusters** — sets of items whose predicted
   touchpoints don't overlap. This is the safety property: only fan out work that
   is in *different* clusters concurrently. Two items in the same cluster must run
   sequentially, never in parallel.
3. For each item you intend to delegate, `get_item_details` to read the full spec,
   blockers, and linked memory, and `related_work` to see the code-neighborhood.
4. Delegate one cluster member at a time:
   - Frontend-only work (`web/**`) -> `gb-frontend`.
   - Everything else -> `gb-implementer`.
   - Open questions / "where does X live" -> `gb-scout` first, fold the answer into
     the delegation prompt.
   Because subagents start with a **clean context window**, put everything the
   worker needs *in the delegation prompt*: the item id, the spec summary, the
   predicted touchpoints, and the relevant invariant (e.g. "this adds an MCP tool —
   follow the MCP task-class checklist: outputSchema + count assertions + docs").

## Rules

- Never delegate two items from the **same** cluster in parallel — that's a
  guaranteed collision. Cross-cluster items are safe to run at once.
- Don't claim items yourself — the worker calls `claim_next` / claims the specific
  id so the lease is held by whoever does the work.
- Respect `blocked_by`: never delegate an item with unfinished dependencies.
- After a worker finishes, re-run `next_cluster` — landed touchpoints refine the
  prediction, so the safe-to-parallelize set changes.""",
    },
    {
        "name": "gb-implementer",
        "description": (
            "Use to implement one scoped backend/general Graphban work item "
            "end-to-end. Claims the item, reads its context, makes the change "
            "following the service-layer invariants, runs the full test loop on both "
            "DB engines, and moves it to review. Cheap model, writes code."
        ),
        "tier": "cheap",
        "readonly": False,
        "is_background": False,
        "body": """You implement **one** Graphban work item, correctly, following the canonical
loop. You start with a clean context window — pull what you need from the
Graphban MCP tools rather than guessing.

## Loop

1. **Claim.** `claim_next` (or claim the specific id the planner gave you). The
   claim is a lease — hold it, don't work unclaimed items.
2. **Load context.** `get_item_details` for the full spec, blockers, and linked
   memory shards. `get_context` for project state. `related_work` for the items
   sharing your touchpoints (don't undo a neighbor's work).
3. **Locate code.** `search_code` and `get_code_map` to find the real files/symbols
   before editing. Confirm the touchpoints match the item's predicted areas; if you
   must touch a file well outside them, stop and flag it — you may be colliding.
4. **Implement one scoped change.** Match surrounding style. Obey the invariants
   below. Call `heartbeat` periodically on longer work so the lease doesn't go stale.
5. **Run the operating loop — a change is NOT done until BOTH engines pass:**
   ```bash
   # from backend/  (pytest is NOT on host PATH)
   ./.venv/bin/python -m pytest -q                     # SQLite, ~45s
   # Postgres+pgvector — the only run that executes real <=> SQL + migrations:
   DATABASE_URL="postgresql+psycopg://postgres:postgres@localhost:5544/graphban_test" \\
     ./.venv/bin/python -m pytest -q
   ```
   If you touched `web/`, delegate to `gb-frontend` or run `pnpm test && pnpm typecheck`
   from `web/`.
6. **Close out.** `update_item` -> `review` (or `blocked` with the reason if you hit
   a wall; `release_item` if abandoning). `extract_lessons` to capture anything the
   next agent should know.

## Invariants (violating these is the review comment you'll get)

- **One service layer** — call/extend functions in `backend/app/services/`; never
  duplicate domain logic in a router or tool handler.
- **Adding/changing an MCP tool?** Entry in `backend/app/mcp_server.py` `TOOLS`
  (with `outputSchema`) + handler branch calling a service fn; update the count
  assertions in `tests/test_api.py` and `tests/test_phase4.py`; update the table in
  `docs/mcp.md`; add a JSON-RPC round-trip test.
- **Schema change?** Edit `backend/app/models/__init__.py`, then
  `alembic revision --autogenerate` and **review the generated migration by hand**
  (pgvector columns + raw-SQL indexes autogen wrong; indexes are HNSW not ivfflat).
  Never edit an applied migration. Verify the chain from empty via the Postgres run.
- **AI providers only via `backend/app/providers/`** (lazy cloud imports; offline
  stub is default). **Enums live in services** — reference, don't inline.

Keep scope tight: one item, one coherent change. If the item is bigger than it
looked, `update_item` with what you found and let the planner re-slice it.""",
    },
    {
        "name": "gb-frontend",
        "description": (
            "Use to implement a scoped frontend (web/) Graphban work item — a React "
            "view, feature, or UI fix. Claims the item, follows the api.ts/queries.ts "
            "data-access invariant, and runs frontend tests + typecheck. Cheap model, "
            "writes code under web/."
        ),
        "tier": "cheap",
        "readonly": False,
        "is_background": False,
        "body": """You implement **one** frontend work item under `web/` (React + TypeScript,
Tailwind v4, Radix UI, lucide-react, TanStack Query). Clean context window — pull
what you need before editing.

## Loop

1. `claim_next` / claim the given id.
2. `get_item_details` + `get_context`; `related_work` to see neighbors sharing your
   touchpoints.
3. `search_code` / `get_code_map` to find the real components before editing.
4. Implement one scoped change following the frontend invariants below.
   `heartbeat` on longer work.
5. **Run the loop — from `web/`:**
   ```bash
   pnpm test && pnpm typecheck        # build with: pnpm build
   ```
   Not done until both pass.
6. `update_item` -> `review` (or `blocked` + reason). `extract_lessons`.

## Frontend invariants

- **Data access only via `web/src/lib/api.ts` + `web/src/lib/queries.ts`**
  (TanStack Query). Never fetch in a component. **Query keys must include the active
  project id** — a view scoped to the wrong project is the bug you'll ship otherwise.
- New route -> register in `web/src/App.tsx`; feature dir under `web/src/features/`.
- A test rendering a view that uses `useProjectCtx` must wrap in `<ProjectProvider>`
  and mock `api.projects`.
- Docs overlay: register the route in `web/src/features/docs/content.ts`.
- Match the existing design grammar (dark theme, lime accent, `rounded-[13px]`
  `bg-surface-2`/`border-line-2` cards, mono-uppercase micro-labels). Reuse tokens
  and existing primitives from `web/src/components/ui/`; don't invent new ones.

Backend change needed too? Hand it back to the planner or `gb-implementer` — keep
this agent's diff inside `web/`.""",
    },
    {
        "name": "gb-scout",
        "description": (
            "Use for read-only research on the Graphban codebase — \"where does X "
            "live\", \"how does Y work\", \"what already touches Z\". Answers from the "
            "code map, code search, and memory without writing anything. Cheap "
            "long-context model; returns findings for the parent to act on."
        ),
        "tier": "cheap",
        "readonly": True,
        "is_background": False,
        "body": """You answer a specific research question about the Graphban codebase and return
findings. You **never** write code, claim items, or change tracker state.

## How to answer

- `search_code` — semantic + text search over the code graph for symbols/behavior.
- `get_code_map` — the structure around a file/module (bounded; don't dump the whole
  graph).
- `related_work` — items whose touchpoints overlap the area, so the parent knows what
  else is in flight there.
- `search_memory` — prior lessons/decisions about this area (often the fastest answer).
- `search_items` — has this already been scoped or done?

## Output

Return a tight answer the parent can act on without re-deriving it:
- The concrete files/symbols (as `path:line` where you can) that answer the question.
- The relevant invariant or gotcha if the area has one (e.g. "this is a service in
  `backend/app/services/` — callers must go through it, not around it").
- Any in-flight or prior work you found (item ids), so the parent doesn't collide or
  duplicate.

Be specific over exhaustive. If the question is ambiguous, state the interpretation
you answered and note the alternative.""",
    },
    {
        "name": "gb-verifier",
        "description": (
            "Use to verify an Graphban change is actually done — runs the full "
            "operating loop on both database engines plus the frontend checks and "
            "reports pass/fail. Does not edit source. Cheap model; good as a "
            "background agent after an implementer finishes."
        ),
        "tier": "cheap",
        "readonly": True,
        "is_background": True,
        "body": """You verify that a change meets Graphban's definition of done. You run the loop
and report — you do **not** edit source to make it pass (that's the implementer's job;
hand failures back).

## Run the full loop

```bash
# Backend — SQLite (from backend/; pytest is NOT on host PATH)
./.venv/bin/python -m pytest -q

# Backend — Postgres+pgvector: the ONLY run that executes real <=> SQL + migrations.
# Bring the DB up if needed:
docker run -d --name gb-pg -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres \\
  -e POSTGRES_DB=graphban_test -p 5544:5432 pgvector/pgvector:pg16
DATABASE_URL="postgresql+psycopg://postgres:postgres@localhost:5544/graphban_test" \\
  ./.venv/bin/python -m pytest -q

# Frontend (from web/)
pnpm test && pnpm typecheck
```

## Definition of done (report against this)

- **Both** database engines pass — SQLite alone is not sufficient; a change is not
  done until the Postgres run (real vector SQL + the Alembic chain from empty) is
  green too.
- Frontend `test` + `typecheck` pass if `web/` was touched.

## Report

- pass / fail per check, with the failing test names + the relevant output excerpt
  for any failure (not the whole log).
- If the Postgres image pull times out (a known Docker Hub flake, not a code defect),
  say so explicitly and suggest a re-run — don't report it as a test failure.
- Do not flip the item's status yourself; return the verdict so the implementer or
  planner decides `review` -> `done` or back to work.""",
    },
]


def render_readme(invariants: str, defaults: str) -> str:
    rows = "\n".join(
        [
            "| Agent | Tier | Writes? | Role |",
            "| --- | --- | --- | --- |",
            "| `gb-planner`     | frontier | no  | Pick + partition **non-colliding** work; delegate to workers |",
            "| `gb-implementer` | cheap    | yes | Backend/general workhorse — claim -> build -> both-DB tests -> review |",
            "| `gb-frontend`    | cheap    | yes | `web/` specialization + frontend invariants |",
            "| `gb-scout`       | cheap    | no  | Read-only research — \"where does X live / how does Y work\" |",
            "| `gb-verifier`    | cheap    | no  | Runs the full operating loop, reports pass/fail |",
        ]
    )
    return f"""# Graphban sub-agent fleet (generated)

{GENERATED_NOTE}

## The idea: context is what lets cheap models build

A non-frontier subagent starts in a **clean context window** — it can't backfill
missing project knowledge the way a frontier model does. Graphban's MCP tools
hand it exactly the context it needs (item spec, related work, code map, memory)
at a tight token footprint, so the cheap model can build correctly. **Frontier
models plan and review; cheap models build.**

{rows}

Each toolchain gets a **native** file — same prompt body, that tool's own format:

| Tool | Role file | Tier → model knob | Read-only via |
| --- | --- | --- | --- |
| Cursor      | `.cursor/agents/*.md` (frontmatter) | `inherit` / `composer-2`              | `readonly: true` |
| Claude Code | `.claude/agents/*.md` (frontmatter) | `inherit` / `haiku`                   | prompt body — tools inherit so the Graphban MCP stays available |
| Codex       | `.codex/agents/*.toml` (TOML role)  | `model_reasoning_effort` `high`/`low` | `sandbox_mode = "read-only"` |

`gb-planner` stays frontier (`inherit`) so it rides whatever strong model the human
is driving; the workers pin to the cheap tier. Repin a tier in the `CURSOR_MODEL` /
`CLAUDE_MODEL` / `CODEX_EFFORT` maps in `scripts/gen_subagents.py` — the bodies never
change.

## The loop every writing agent follows

`claim_next` -> `get_context` / `get_item_details` -> `search_code` / `get_code_map`
for touchpoints -> implement one scoped change -> **run the operating loop (both DB
engines)** -> `update_item` to `review` -> `extract_lessons`. `heartbeat` while
working; `release_item` if abandoning. The claim is the lease that keeps parallel
workers off each other's files — `gb-planner` only fans out clusters that don't
overlap.

## Non-negotiables (verbatim from AGENTS.md — every agent obeys)

{invariants}

## Design defaults (verbatim from AGENTS.md — argue with them if you have a reason)

{defaults}
"""


def render_plugin_files() -> dict[str, str]:
    """The Cursor plugin: manifest, README, and the fleet role agents.

    Deliberately NO `mcp.json`. Credentials are per-install, Cursor does not interpolate them
    from the environment, and a committed file cannot carry them — so the config comes from the
    Fleet view, which has the keys at mint time. Shipping a placeholder `mcp.json` here would
    be a generated file every user has to hand-edit, which is what `--check` exists to prevent.
    """
    import json

    manifest = {
        "$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",
        "name": "graphban",
        "version": "1.0.0",
        "description": (
            "Graphban fleet roles for Cursor. Mint a wave in the Fleet view for the MCP "
            "config; this ships the agents that use it."
        ),
        "author": {"name": "Graphban"},
        "keywords": ["graphban", "fleet", "mcp"],
    }
    files = {
        f"{PLUGIN_DIR}/plugin.json": json.dumps(manifest, indent=2) + "\n",
        f"{PLUGIN_DIR}/README.md": render_plugin_readme(),
    }
    ext, render = RENDERERS["cursor"]
    for role in FLEET_ROSTER:
        files[f"{PLUGIN_DIR}/agents/{role['name']}{ext}"] = render(role)
    return files


def render_plugin_readme() -> str:
    return f"""# Graphban for Cursor (generated)

{GENERATED_NOTE}

Cursor stores **one** MCP config and reuses it across every agent, so a per-role credential has
nowhere to live: one key for everybody, and the server then refuses every review — a reviewer
sharing its author's credential is not a second opinion.

Cursor *does* hold several server entries with different keys. So the fleet works there, with
one config naming three role-narrowed credentials.

## Install

    ln -s "$(pwd)/{PLUGIN_DIR}" ~/.cursor/plugins/local/graphban

Then restart Cursor. This ships the role **agents**; the MCP config comes from the Fleet view.

## Each wave

**Fleet view -> Provision a whole wave.** It mints planner, worker and reviewer credentials and
emits the whole `~/.cursor/mcp.json` with the keys in it. Paste, restart Cursor.

There is no environment-variable form. Cursor does not interpolate `${{env:VAR}}`, `${{VAR}}` or
`$VAR` in `mcp.json` — probed against 3.16.2 with the variables present in the process
environment, and the entry is silently **dropped** rather than sent as a literal. A config that
looks right and connects nothing is worse than one you regenerate each wave.

Wave credentials expire, and **End wave** revokes them — which is what makes keys in a config
file an acceptable trade here.

## If you must share one credential

Then roles are advisory, and every agent has to declare who it is:

    register_agent(label=..., capabilities={{"instance": "<unique per agent>"}}, role_hint=...)

On one credential an agent that declares nothing that differs is refused review. That is
deliberate: absence is not a difference, or omitting a field would launder a self-review.

## What this does and does not guarantee

With a wave, each server carries a genuinely role-narrowed credential, so a worker reaching for
`sign_off` is refused and a reviewer signing a worker's item is independent.

**Cursor cannot scope an MCP server to one agent.** Every agent sees all three, so one that
deliberately switches servers can still sign off its own work. What changes is the default:
sharing one unrestricted key refuses nothing, and here the wrong call fails unless somebody
goes out of their way. Treat it as coordination, not as an adversarial boundary.
"""


def render_files() -> dict[str, str]:
    """Return {relative_path: content} for every generated file, all toolchains."""
    agents_md = AGENTS_MD.read_text()
    invariants = extract_section(agents_md, "Invariants")
    if not invariants:
        raise SystemExit("could not extract '## Invariants' from AGENTS.md")
    # The fleet writes most of the code, so a design default it never sees shapes
    # nothing. Carried verbatim for the same reason the invariants are: a paraphrase
    # here would drift from AGENTS.md and nothing would catch it.
    defaults = extract_section(agents_md, "Design defaults")
    if not defaults:
        raise SystemExit("could not extract '## Design defaults' from AGENTS.md")

    readme = render_readme(invariants, defaults)
    files: dict[str, str] = {}
    for tool in TOOLCHAINS:
        ext, render = RENDERERS[tool]
        files[f".{tool}/agents/README.md"] = readme
        # Fleet roles emit exactly like the in-session ones — same renderers, same `--check`
        # staleness gate. PRD-17 §9: the client half gets EXTENDED, not replaced.
        for role in ROSTER + FLEET_ROSTER:
            files[f".{tool}/agents/{role['name']}{ext}"] = render(role)
    files.update(render_plugin_files())
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 if stale")
    args = ap.parse_args()

    files = render_files()
    if args.check:
        stale = []
        for rel, content in files.items():
            path = REPO / rel
            if not path.exists() or path.read_text() != content:
                stale.append(rel)
        if stale:
            print("Sub-agent fleet is stale — run `python scripts/gen_subagents.py`:")
            for rel in sorted(stale):
                print(f"  - {rel}")
            return 1
        print(f"Sub-agent fleet up to date ({len(files)} files across {len(TOOLCHAINS)} toolchains).")
        return 0

    for rel, content in files.items():
        path = REPO / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    print(f"Wrote {len(files)} files across {len(TOOLCHAINS)} toolchains.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
